### ISSUE TITLE
running the game

### ISSUE THREAD

**Issue by whitefox11235** [sameerlal/OMakeMeAMarket#1]
Ciao sameerlal
im having difficulties in running your game.  
<img width="565" alt="Screenshot 2021-01-03 at 14 33 37" src="https://user-images.githubusercontent.com/76907621/103479841-b929e900-4dd0-11eb-815e-d6e7c864090c.png">

Can you help me pls?
thanks

**Comment by sameerlal** [comment]
You need to install ocamlbuild: https://github.com/ocaml/ocamlbuild
Try with opam:
`opam install ocamlbuild`

**Comment by whitefox11235** [comment]
thanks! I've installed it but now I got this: 
<img width="879" alt="Screenshot 2021-01-03 at 19 52 48" src="https://user-images.githubusercontent.com/76907621/103486347-7fbba280-4dfd-11eb-9355-7bc7fa2b0b49.png">

thanks for your help
![Uploading Screenshot 2021-01-03 at 19.52.48.png…]()

**Comment by sameerlal** [comment]
Can you try: 
`eval $(opam config env)` ?
If that doesn't work, try

> eval `opam config env`
(use single tick marks ` around the "opam config env")


Alternatively, you might have to revert to a previous version of opam:
`opam switch 4.02.3  `
`eval $(opam config env)`
`opam install ocamlfind `

**Comment by lorcanoconnor** [comment]
![image](https://user-images.githubusercontent.com/10981979/148458607-e9fd8dc1-e4b6-4262-ba2f-a9f37dd7e9af.png)
what's going on!!? please help

**Comment by sameerlal** [comment]
I'll work to clean this up / migrate this

**Comment by sameerlal** [comment]
@Lorcanosaurus @whitefox11235 
Hi, pls see: https://github.com/sameerlal/MarketMakingGame

**Comment by avblink** [comment]
Hi,

any progress on this?
I was trying to run the game, followed the instructions and ended up with the same error

File "gui.ml", line 45, characters 16-36:
Error: Unbound value String.split_on_char

Can you maybe post a compiled version?
Can it be run on Windows?
