### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ElwinKardux** [sameerlal/OMakeMeAMarket#3]
Hi,

For some reason I keep getting a segmentation fault when i try to run 'make play'. 
Make clean and make build however do seem to work. I haven't found any way to resolve this issue.
![image](https://user-images.githubusercontent.com/57056550/110037345-910e2600-7d3e-11eb-9da7-f9f53623d6df.png)
A moderator from the OCaml discord reckoned this might be a crash in the code. Does anyone have any clue how to fix this?

**Comment by sameerlal** [comment]
@ElwinKardux Pls see: https://github.com/sameerlal/MarketMakingGame
