### ISSUE TITLE
OMakeMeAMarket_Updated

### ISSUE THREAD

**Issue by junioranalyst1** [sameerlal/OMakeMeAMarket#4]
Tried to run the game first time around and it didn't work. Had to update parts of the code for ounit2. Now it runs fine.

For anyone interested, just run:
git clone https://github.com/junioranalyst1/OMakeMeAMarket_Updated.git
cd OMakeMeAMarket_Updated
eval $(opam env)
make clean && make build && make play

**Comment by sameerlal** [comment]
Hey! thanks for this. I meant to update this project a while ago, but haven't had the time.  Do you mind creating a pull request with your changes? I'll give you credit for this update.

Cheers, Sameer

**Comment by junioranalyst1** [comment]
Thanks! Just created the pull requests.

**Comment by avblink** [comment]
![image](https://user-images.githubusercontent.com/14271824/190189161-65e09cfc-9938-44ee-9687-1b069832e907.png)


I get this error.
